version: "3.7"
services:
  mongo:
    image: mongo:latest
    command: mongod --port 27017
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db    
  ludum-duvida:
    image: guilhermesiqueira/ludum-duvida
    ports:
      - "8080:8080"
    links:
      - mongo
